### ISSUE TITLE
Only works for just one button

### ISSUE THREAD

**Issue by LeichtfriedSebastian** [crunchysteve/EdgieD#1]
Is it also possible to use the library for edge detection also at more than one button?

When i tried it, it doesn't work any more.

**Comment by crunchysteve** [comment]
Yes, when instantiating the library create an object for each button...

``` C
Edge buttonOne;
Edge buttonTwo;
// etc, for each button (good idea to name each instance for the button function)
```

then, detect edges by regularly calling

``` C
buttonOne.detect(edge);
buttonTwo.detect(edge);
// where 'edge' would be 1 or 0, HIGH or LOW, TRUE or FALSE _or_ Rising or Falling  (built in library macros)
// for the edge state you're testing for
```

Cheers,
Crunchy.

**Comment by LeichtfriedSebastian** [comment]
Hey Crunchy,

thank you for answering my question...but it still doesn't work. Maybe i have a mistake in the code. But as I said earlier, this method works with just one button. But in real life i need much more than one button.

Maybe you see a mistake in the code and could help me... Thank you!


#include <Controllino.h>
#include <Wire.h>
#include <BlockNot.h>
#include <neotimer.h>
#include <EdgieD.h>

int diButtonPin = CONTROLLINO_DI0;
int diButtonSmallPin = CONTROLLINO_DI1;
int rdoLedRedPin = CONTROLLINO_R0;


bool diButton = 0;
bool diButtonSmall = 0;
bool LedState;

Edge MyEdgeButton;
Edge MyEdgeButtonSmall;


void setup() {
  Serial.begin(9600);

  pinMode(diButtonPin,INPUT);
  pinMode(diButtonSmallPin, INPUT);
  pinMode(rdoLedRedPin,OUTPUT);

  digitalWrite(rdoLedRedPin,LOW);
  LedState = 0;
}

void loop() {
  diButton = digitalRead(diButtonPin);
  diButtonSmall = digitalRead(diButtonSmallPin);


//Button 1 (Big one)
  if(MyEdgeButton.detect(diButton,Rising) == 1){
    if (LedState == 0){
      digitalWrite(rdoLedRedPin,HIGH);
      LedState = 1;
    }
    else{
      digitalWrite(rdoLedRedPin,LOW);
      LedState = 0;
    }
  }


//Button 2 (Small one)
  if(MyEdgeButtonSmall.detect(diButtonSmall,Rising) == 1){
    if (LedState == 0){
      digitalWrite(rdoLedRedPin,HIGH);
      LedState = 1;
    }
    else{
      digitalWrite(rdoLedRedPin,LOW);
      LedState = 0;
    }
  }

  delay(10);
}

**Comment by crunchysteve** [comment]
I've got a busy weekend, I can have a proper look on Monday. (I'm an
amateur, this was my first ever library contrib. (I don't do this for a
living.) In fact yours is my first ever issue. Thanks for trying the
library, I hope we can get this sorted quickly and to your satisfaction.

Meanwhile, I see you're trying to use a Controllino micro. I have no
experience with this board (they look like a cool product) but their
website says "completely compatible with Arduino," so maybe the problem is
addressing the pins as CONTROLLINO_DI0, etc. Usually Arduino compatible
pins are addressed directly as D10 or D11, etc, depending on the pin in
use. Another thing to look at in the meantime, are...
1. try simplifying the code down to address the button pin reads directly.
Even if your scope requires those specific steps, making a simpler version
might help find where the bug is. Simpler direct code (and it still doesn't
work) it's likely my code.
2. how are your buttons wired? Are they sending 5v logic to the pin
directly when pressed, or are they pullups, where a resistor holds the
input high and the button press pulls them low? If they're pullups your
code as to set pinMode(pin,INPUT_PULLUP).

Anyway, let me me know if these checks help or not and I'll get into full
debug mode on Monday. My time zone is Eastern Australian so, depending on
where you are, I may be starting before you wake (Central Asia to Europe)
or after. (Pacific to US)

Cheers,
Crunchy

**Comment by crunchysteve** [comment]
I also need to ask, did you use Controllino's AI code generator to generate
this code?

Cheers

**Comment by LeichtfriedSebastian** [comment]
Dear Crunchy,
no problem, I just don't like to disturb you. Please don't stress about this problem

You have to know that I am also no Pro working with these arduino products. In fact I'm an industrial PLC Programmer. So I work with Siemens (programming language FUP or ST). I use the Controllino products as an alternative for small industrial applications. They fully meet the IEC 61131 (that's very important). In this case I use an Controllino MAXI with the standard  ATmega 2560-16AU chip. So it is totally Arduino compatible. 

By the way...I also tried the same programm with the Arduino Uno, and it also doesn't work. 

You have to know that this programm is just a random testing example. You can also test it with an counter or something like that. 
I use the 24V Pins of the Controllino, so no Input Pullup (I'm not such an extreme beginner that I don't know the differences ;)

I've never tried the AI code generator.

My time zone is Central European Time. 

Thank you very much for your efforts!

Best Regards
Leichtfried Sebastian

**Comment by crunchysteve** [comment]
Thank you so much for the info. That's useful to know, I'll Look into this
on Monday.

**Comment by crunchysteve** [comment]
Hi Sebastian (I'm assuming Sebastian is your first name, or is it
Leichtfried? Apologies if I've got that wrong...),

Yeah, this is weird, it works for a single button and not 2 buttons and all
I can think is that I broke something between between 1.0.0 and 1.0.1 (a
minor bugfix that wasn't even related to this) I've tested on a 328p board
(nano) and on Wokwi.com (uno) and can't get it to do 2 instances or cascade
internal logic signals.

I'm looking at my code and can't see how I've made it behave like
"singleton", so this is going to take some time to fix. Like I say, I'm
very much an amateur, and what I'm going to do is recommend the Bounce2
(Arduino recommended) or Bugtton, which are specifically designed for
button debouncing, whereas mine is more specifically for fast signal edge
detection of code variable states, for frequency division and time
multiplying, so I'm using a simpler, faster algorithm. This project has
been pushing the limits of my C++ understanding, so I feel obliged to
suggest these other libraries as they're proven tools, while mine's a bit
of a hack, still. Code usage is very easy, here's Bounce2's BounceTwo.ino
code example

``` C
/*
DESCRIPTION
====================
Simple example of the Bounce library that switches the debug LED when
either of 2 buttons are pressed.
*/
// Include the Bounce2 library found here :
// https://github.com/thomasfredericks/Bounce2
#include <Bounce2.h>

#define BUTTON_PIN_1 2
#define BUTTON_PIN_2 3

#define LED_PIN 13

// Instantiate a Bounce object
Bounce debouncer1 = Bounce();

// Instantiate another Bounce object
Bounce debouncer2 = Bounce();

void setup() {
  // Setup the first button with an internal pull-up :
  pinMode(BUTTON_PIN_1,INPUT_PULLUP);
  // After setting up the button, setup the Bounce instance :
  debouncer1.attach(BUTTON_PIN_1);
  debouncer1.interval(5); // interval in ms
  // Setup the second button with an internal pull-up :
  pinMode(BUTTON_PIN_2,INPUT_PULLUP);
  // After setting up the button, setup the Bounce instance :
  debouncer2.attach(BUTTON_PIN_2);
  debouncer2.interval(5); // interval in ms

  //Setup the LED :
  pinMode(LED_PIN,OUTPUT);
}

void loop() {
  // Update the Bounce instances :
  debouncer1.update();
  debouncer2.update();

  // Get the updated value :
  int value1 = debouncer1.read();
  int value2 = debouncer2.read();

  // Turn on the LED if either button is pressed :
  if ( value1 == LOW || value2 == LOW ) {
  digitalWrite(LED_PIN, HIGH );
  } else {
    digitalWrite(LED_PIN, LOW );
  }
}
```

My apologies for the inconvenience, but also thanks for alerting me to the
existence of the Controllino devices. They look industrial enough for my
CNC upgrade project. I hope you're not too disappointed.

Cheers,
Crunchy.
